#A list of indestructible blocks that will always count as support and never fall themselves.
indestructibleBlocks = ["minecraft:bedrock", "minecraft:command_block", "minecraft:barrier", "minecraft:structure_block", "minecraft:structure_void", "minecraft:reinforced_deepslate", "minecraft:end_portal_frame"]
#A list of dimensions allowed to have physics behavior. The Nether, and especially the End, are not recommended as both can easily experience catastrophic structural failure.
allowedDimensions = ["minecraft:overworld"]
#Block Break Volume (caused by mod).
#Range: 0.0 ~ 1.7976931348623157E308
blockBreakVolume = 1.0
#Support Strength Max. This value will be used by anything with a default hardness equal to or greater than 7 (iron blocks, obsidian, etc...).
#Range: > 1
supportLengthMax = 10
#Support Strength Min. This value will be used by anything with a default hardness equal to 0 (honey blocks, slime blocks, etc...).
#Range: > 1
supportLengthMin = 1
#Base block entity fall damage inflicted per block fallen.
#Range: > 0
dmgDist = 1
#Max block entity fall damage inflicted. Max is taken from support strength (i.e. falling obsidian hurts more than dirt), but is overwritten if greater than this value.
#Range: > 0
dmgMax = 10
#Max number of falling entities allowed to be generated by the mod at any one time. Blocks that should 'fall' will wait to avoid exceeding this number. Lower for better performance, raise for faster collapses, set to 0 to turn the mod off.
#Range: > 0
maxFallingBlockEntity = 5000
#Max number of iterative supports to scan.
#Range: > 0
supportSearchIter = 4
#A factor influencing the chance of a falling block to break on ground contact, rather than be placed or shift over, which is also influenced by speed. Increase this value to make contact breaks more frequent (1 will always break), and decrease to make them less frequent (0 will never break).
#Range: 0.0 ~ 1.0
fallingBlockBreakFactor = 0.5
#Percent chance that a destroyed falling block will drop its item. 100 will always drop, 0 will never drop.
#Range: 0.0 ~ 1.0
fallingBlockItemDropChance = 0.0
#Causes collapsing blocks to be destroyed directly instead of generating a falling block entity. Dramatically improves performance. Uses fallingBlockItemDropChance to determine how often they should drop their item. Uses maxFallingBlockEntity to determine how many blocks to allow to break per tick.
removeBlocksInsteadOfFall = false
#A list of vanilla blocktags to assign custom support strength values (rather than the hardness-based default). Listed blocktags without a matching support value at its index (below) will use default values.
overwriteBlockTags = ["minecraft:leaves"]
#A list of support strength values to override native (hardness based) blocktag support strength, matched by index (order) to above list.
overwriteBlockTagValues = [4]
#As the blocktag list above, but with individual blocks. Specified blocks will overwrite both default and blocktag specified support values.
overwriteBlocks = ["minecraft:netherrack"]
#A list of support strength values to override native (hardness based) individual block support strength, matched by index to above list.
overwriteBlockValues = [4]

